name: Compile Script
on:
  push:
  pull_request:

jobs:
  lint-and-compile:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -r requirements.txt
      - run: pyinstaller --onefile --distpath dist --workpath build --clean --icon NONE --name CheckSongs check_songs.py
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: CheckSongs
          path: dist\*
